package exceptionhandling;

public class ErrorDemo {

	public void m1()
	{
		m2();
	}
	
	public void m2()
	{
		m1();
	}
	
public static void main(String [] args) {	
	
	ErrorDemo ed = new ErrorDemo();
	ed.m2();// this will lead to stack overflow since the method are called in a cyclic manner
	
    }
	
	
	
}
//error-->  AN UNEXPECTED OR UNWANTED EVENT WHICH IS CALLED DUE TO THE DEFIENCY OF THE SYSTEM IS CALLED ERROR (SYNTAX IS CORRECT BUT LOGICALLY IT IS INCORRECT)

// WHAT IS DIFFERENCE BETWEEN ERROR AND EXCEPTION? 
// ERROR IS AN EVENT WHICH OCCUE DUE TO SYSTEM PERFORMANCE DUE TO WHICH IT LEADS TO ABNORMAL TERMINATION IS CALLED ERROR
// EXCEPTION--> AN UNEXPECTED EVENT WHICH OCCUR DUE TO LOGIC USED N LEADS TO ABNORMAL TERMINATION CALLED AS EXCEPTION

// ERROR IS BASSICALLY A CLASS IN JAVA WHICH HAS MULTIPLE CHILD CLASSES THET ARE 
// 1.STACKOVERFLOWERROT
//2. ASSERTION ERROR

//TO RESOLVE THE ERROR WE HAVE TO IMPRVE THE SYSTEM PERFORMANCE SO THAT WE SHOULD MINIMIZE THE CHANCE OF ERROR 